# Generated by Django 4.2.3 on 2025-09-23 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_studentpresencerecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentemotionrecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentemotionrecord',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='studentpresencerecord',
            name='student',
        ),
        migrations.RemoveField(
            model_name='studentpresencerecord',
            name='teacher',
        ),
        migrations.DeleteModel(
            name='StudentDrowsinessRecord',
        ),
        migrations.DeleteModel(
            name='StudentEmotionRecord',
        ),
        migrations.DeleteModel(
            name='StudentPresenceRecord',
        ),
    ]
